/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractAddresses_11155111 } from './11155111'
import { ContractAddresses_1337 } from './1337'
export type ContractAddressesKey = keyof typeof ContractAddresses
export const ContractAddresses = {
  11155111: ContractAddresses_11155111,
  1337: ContractAddresses_1337,
}
