/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PooledTemplate } from "./PooledTemplate";
export type { TestERC20 } from "./TestERC20";
export type { TrustedPool } from "./TrustedPool";
