/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PooledTemplate__factory } from "./PooledTemplate__factory";
export { TestERC20__factory } from "./TestERC20__factory";
export { TrustedPool__factory } from "./TrustedPool__factory";
